server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=yes&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cz.cloud.user.sign
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

